version: 1

workflows:
  app-store-release:
    name: App Store Release Build
    description: Build and upload to App Store Connect with latest iOS SDK
    
    trigger:
      push:
        branches:
          - main
          - master
    
    environment:
      xcode: latest
      macOS: latest
    
    build:
      scheme: ProgressBuild
      configuration: Release
      destination: generic/platform=iOS
      
    archive:
      scheme: ProgressBuild
      configuration: Release
      
    distribute:
      - destination: app-store-connect
        groups:
          - App Store Connect Users

  manual-release:
    name: Manual Release Build
    description: Manually triggered build for App Store
    
    trigger:
      manual: true
    
    environment:
      xcode: latest
      macOS: latest
    
    build:
      scheme: ProgressBuild
      configuration: Release
      destination: generic/platform=iOS
      
    archive:
      scheme: ProgressBuild
      configuration: Release
      
    distribute:
      - destination: app-store-connect
        groups:
          - App Store Connect Users
