version: 1

workflows:
  app-store-release:
    name: App Store Release Build
    description: Build and upload to App Store Connect with iOS 18 SDK
    
    trigger:
      push:
        branches:
          - main
          - master
    
    environment:
      xcode: latest
      macOS: latest
    
    build:
      scheme: ProgressBuild
      configuration: Release
      destination: generic/platform=iOS
      
    archive:
      scheme: ProgressBuild
      configuration: Release
      
    distribute:
      - destination: app-store-connect
        groups:
          - App Store Connect Users

  development-build:
    name: Development Build
    description: Build for testing
    
    trigger:
      pull_request:
        target_branches:
          - main
          - master
    
    environment:
      xcode: latest
      macOS: latest
    
    build:
      scheme: ProgressBuild
      configuration: Debug
      destination: platform=iOS Simulator,name=iPhone 15
